### ISSUE TITLE
Removing a sketch on safari and Firefox issues

### ISSUE THREAD

**Issue by mjanssen** [processing/p5.js#1062]
When removing a sketch on the Safari browser, an issue is logged in the console which crashes the application. The logged error is
`InvalidStateError: DOM Exception 11: An attempt was made to use an object that is not, or is no longer, usable.`

On Firefox, there is an error logged which states
`TypeError: Not enough arguments to EventTarget.removeEventListener.`

On Chrome, everything works as it should work.

Link to reproduce the error (When files are loaded, music starts playing. When clicking 6 times, the sketch should be removed and music stops playing (error is shown)):
http://codepen.io/marnixelmo/pen/GpdVBG

**Comment by toolness** [comment]
I think that the Firefox error may have just been fixed by #1054, possibly?

**Comment by toolness** [comment]
Yep, #1054 fixed it--just ran the codepen example, but replaced its p5 with the latest master as of 00782f4f06e7f1725a6cdab535a04d2938e00bea, and it works fine on Firefox. Also saw the traceback on a pre-#1054 revision of p5 and confirmed that the crash occurs where the changes in #1054 were made.

Not sure if the bug is still present on Safari or not, though.

**Comment by mjanssen** [comment]
The issue still persists on Safari (with the [#1059](https://github.com/processing/p5.js/pull/1059) pull). Firefox seems to be functional.

**Comment by toolness** [comment]
Hmm, so the Safari crash seems to be coming from p5.sound.js, and I'm not familiar enough with that library or the Web Audio API to debug it very easily.

However, I did notice that the DOM exception only seems to be raised if one of the sound files is actually *playing* at the time that the sketch is removed. This can be shown by either waiting a few seconds between each click, or commenting-out the `.play()` call in the `c.mousePressed` handler in the codepen.

Sorry I can't help more with this one...

**Comment by lmccart** [comment]
thanks for looking into this @toolness! pinging @therewasaguy here... i have some time to look into this more closely later this week and determine if it is an issue with p5.sound, but in case you want to check it out before then.

**Comment by therewasaguy** [comment]
This looks like an issue with p5.sound, I'll try to fix later today.
