### ISSUE TITLE
loadTable interferes with saveTable

### ISSUE THREAD

**Issue by mikecai011** [processing/p5.js#1238]
I have noticed that if you load a table in preload function, you will not be able to correctly save any table using either "save()" or "saveTable()".

**Comment by DarkPrince304** [comment]
Can you paste the code here? Because I think its working fine on my side?

**Comment by mikecai011** [comment]
var table;
var inTable;
var newRow = new Array();

function preload() {
  inTable = loadTable("test.csv", "csv", "noHeader");
}

function setup() {
  table = new p5.Table();
  for (var c = 0; c <= inTable.getColumnCount(); c++) {
    table.addColumn();
  }
  for (var r = 0; r < inTable.getRowCount(); r++) {
    newRow[r] = table.addRow();
    for (var c = 0; c <= inTable.getColumnCount(); c++) {
      newRow[r].setString(c, inTable.getString(r, c));
    }
  }
  for (var r = 0; r < table.getRowCount(); r++) {
    for (var c = 0; c < table.getColumnCount(); c++) {
      print(table.getString(r, c));
    }
  }
  save(table, "new.csv");
}

function draw() {}

**Comment by mikecai011** [comment]
Even if i replace everything in setup with simply adding one row of data, the save table does not work properlly.

**Comment by mikecai011** [comment]
This is the data i got from my new.csv file. It only has one row.

簑^~)?

**Comment by lmccart** [comment]
I think lines [604-606](https://github.com/processing/p5.js/blob/master/src/io/files.js#L604) are incorrect and should be something like:
`t.columns = records[0];`

in terms of your code, is there a reason you're using <= and not <?
`for (var c = 0; c <= inTable.getColumnCount(); c++) {`

with those two changes it seems to look ok. @therewasaguy any thoughts on the loadTable() change? does this seem ok?

**Comment by mikecai011** [comment]
I used <= because it returns one less column than there is. I think the program assumes the first column is just numbering.

**Comment by lmccart** [comment]
the bug with `loadTable()` should be fixed but I would recommend using `createWriter()` if you are trying to crease a csv output. see this example here:
https://github.com/lmccart/gswp5.js-code/blob/master/Robots/Robot10_Data_a.js

**Comment by mikecai011** [comment]
Change it to
for (i = 0; i < records[0].length; i++) {
          t.columns= records[0];
        }
Still not working for me.

**Comment by mikecai011** [comment]
After trying out a bit, I found that loadTable interferes with createWriter it.  Without loadTable, the window asking you to select saving location successfully pops up.
![image](https://cloud.githubusercontent.com/assets/8644482/13412321/77ec764e-df10-11e5-97a3-b9def678c42f.png)
But with loadTable, a table named "new.csv" automatically shows up in the directory of sketch file and the bug mentioned above occurs.

**Comment by lmccart** [comment]
hey @mikecai011 is this using the p5 editor? trying to figure out if it's a bug in the editor or library..

**Comment by mikecai011** [comment]
Yes, I am using the P5 editor. For the correction you mentioned, I simply found the line and changed it in p5.js file in library folder, which is included in the sketch folder.
![image](https://cloud.githubusercontent.com/assets/8644482/13417468/3da98fe2-df3a-11e5-8671-3b2c75672b9f.png)
