### ISSUE TITLE
text as texture error

### ISSUE THREAD

**Issue by jguess** [processing/p5.js#1464]
There seems to be an error in the text as texture example (http://p5js.org/reference/#/p5/texture)

TypeError: invalid 'instanceof' operand p5.MediaElement
	
else if (args[0] instanceof p5.MediaElement){

p5.js (line 28884, col 1)

**Comment by jguess** [comment]
Am I the only person who has run into this problem ?

**Comment by limzykenneth** [comment]
I have the same problem as well

**Comment by indefinit** [comment]
Looks like the problem has to do with there not being a video file 'myVideo.mp4'.  I seem to recall there being a 'fingers' video somewhere on the site.  Has anyone seen it recently?  Otherwise, we'll need to store a video file somewhere to reference in the docs.

**Comment by jguess** [comment]
Hmm, what would be the workaround to simply use text as a "createGraphics" texture ?

**Comment by limzykenneth** [comment]
@indefinit if it is because of the video being not found, it almost is because the p5.dom.min.js is not loaded in, should be fixed as soon as the new fixed version is pushed up

**Comment by jguess** [comment]
ok !

**Comment by lmccart** [comment]
thanks all, should be fixed now. just a missing vid file. @limzykenneth the minified lib files are fixed as well and available on the site now.

**Comment by jguess** [comment]
it still doesn't work, even on the example page...
http://p5js.org/reference/#/p5/texture

**Comment by jguess** [comment]
ah, it works if you put the location in text !
pg.text("Test", 50, 50);

**Comment by lmccart** [comment]
doh! missed that, good call.
