### ISSUE TITLE
 "video.get()" not working

### ISSUE THREAD

**Issue by eglrd** [processing/p5.js#1588]
```javascript
var eCam;
var eButton;
var eSnapshots = [];

function setup() {
  createCanvas(320, 240);
  background(51);
  eCam = createCapture(VIDEO);
  eCam.size(320, 240);
  eCam.hide();
  eButton = createButton('snap');
  eButton.mousePressed(takeSnap);
}

function takeSnap(){
  eSnapshots.push(eCam.get());
}

function draw() {
  for(var i=0;i < eSnapshots.lenght; i++){
    image(eSnapshots[i], 0, 0, 50, 50);
  }
}
```

triggers
p5.js:12060 Uncaught TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(HTMLImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap)'

on macos with 10.11.6 hosting with node.js 4.5.0, and p5js v0.5.3﻿

**Comment by shiffman** [comment]
I did some digging on this and tested the following code.  It works properly in 0.5.2 but fails in 0.5.3.  I'm going to see if I can pinpoint what changed caused the problem.

```javascript
function setup() {
  createCanvas(320, 240);
  video = createCapture(VIDEO);
  video.size(320, 240);
}

function draw() {
  background(51);
  var snapshot = video.get();
  image(snapshot, 0, 0);
}
```

**Comment by shiffman** [comment]
Ok, after some digging it's this commit that breaks `get()` 8952a7c6869ebeeb385ce5e97adf8efb6fc26dc0.

I'll file a pull request to fix and add `loadPixels()` back in.  (But maybe there's something I am missing, feel free to let me know!)

**Comment by shiffman** [comment]
@hobzcalvin Adding you to this thread as I noticed the commit I'm referencing above (https://github.com/processing/p5.js/commit/8952a7c6869ebeeb385ce5e97adf8efb6fc26dc0) was from your pull request.  Let me know if I've got something wrong here!

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/1616

**Comment by Juarez-BioIT** [comment]
I tried this code today in the p5.js web editor and is still not working

**Comment by lmccart** [comment]
there's a typo in the above code `eSnapshots.lenght` should read `eSnapshots.length`
when I made this change, the code runs in the editor

```js
var eCam;
var eButton;
var eSnapshots = [];

function setup() {
  createCanvas(320, 240);
  background(51);
  eCam = createCapture(VIDEO);
  eCam.size(320, 240);
  // eCam.hide();
  eButton = createButton('snap');
  eButton.mousePressed(takeSnap);
}

function takeSnap(){
  eSnapshots.push(eCam.get());
}

function draw() {
  for(var i=0;i < eSnapshots.length; i++){
    image(eSnapshots[i], 0, 0, 50, 50);
  }
}
```

**Comment by Juarez-BioIT** [comment]
It runs, but it doesn't work as it should. Although the array does get a new element from `eCam.get()`, **it seems that** `eCam.get()` **don't get updated**, so only the first snapshot fills the array.
(Compare with Shiffman's video at 9:47 https://www.youtube.com/watch?v=oLiaUEKsRws&t=555s).

```p5.js
var eCam;
var eButton;
var eSnapshots = [];

function setup() {
  createCanvas(320, 240);
  background(0);
  eCam = createCapture(VIDEO);
  eCam.size(320, 240);
  eButton = createButton('snap');
  eButton.mousePressed(takeSnap);
}

function takeSnap(){
  eSnapshots.push(eCam.get());
}

function draw() {
  var w = 80;
  var h = 60;
  var x = 0;
  var y = 0;
  
  for(var i=0; i < eSnapshots.length; i++){
    //Position of snaps (based on their index)
    x= i*w % width;
    y= floor( i / (width/w) ) * h;
    
    //Each snap have a unique position (no overlapping)
    image(eSnapshots[i], x, y, w, h);
  }
  
  //Notice that the array gets bigger
  print('There are ' + eSnapshots.length + " snapshot(s)")
}
```

**Comment by Spongman** [comment]
I think you might be seeing the same behavior that was reported in #3779. The fix for this should be in the next release.
