### ISSUE TITLE
p5.js webgl canvas not working

### ISSUE THREAD

**Issue by Klibrugak** [processing/p5.js#2508]
All the 2D primitives work fine, but when I try to make a webgl canvas it just stays blank
the web console prints out this:

Uncaught TypeError: Cannot read property 'location' of undefined
    at d.RendererGL.createBuffers (p5.min.js:37)
    at e.d.ellipsoid (p5.min.js:38)
    at draw (cube.js:8)
    at e.d.redraw (p5.min.js:33)
    at e.<anonymous> (p5.min.js:32)
    at e.<anonymous> (p5.min.js:32)
    at new e (p5.min.js:32)
    at e (p5.min.js:32)
d.RendererGL.createBuffers @ p5.min.js:37
d.ellipsoid @ p5.min.js:38
draw @ cube.js:8
d.redraw @ p5.min.js:33
(anonymous) @ p5.min.js:32
(anonymous) @ p5.min.js:32
e @ p5.min.js:32
e @ p5.min.js:32
p5.js:45213 p5 had problems creating the global function "registerPreloadMethod", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "registerMethod", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_createFriendlyGlobalFunctionBinder", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_helpForMisusedAtTopLevelCode", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "alpha", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "blue", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "brightness", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "color", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "green", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "hue", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "lerpColor", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "lightness", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "red", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "saturation", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "background", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "clear", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "colorMode", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "fill", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "noFill", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "noStroke", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "stroke", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "float", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "int", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "str", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "boolean", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "byte", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "char", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "unchar", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "hex", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "unhex", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "append", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "arrayCopy", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "concat", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "reverse", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "shorten", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "shuffle", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "sort", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "splice", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "subset", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "join", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "match", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "matchAll", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "nf", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "nfc", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "nfp", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "nfs", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "split", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "splitTokens", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "trim", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "cursor", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "frameRate", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "getFrameRate", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "setFrameRate", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "noCursor", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_onresize", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "fullscreen", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "pixelDensity", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "displayDensity", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "getURL", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "getURLPath", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "getURLParams", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "createImage", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "saveCanvas", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "saveFrames", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_makeFrame", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "image", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "tint", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "noTint", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_getTintedImageCanvas", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "imageMode", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "blend", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "copy", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "filter", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "get", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "loadPixels", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "set", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "updatePixels", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "parseXML", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "httpGet", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "httpPost", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "httpDo", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "createWriter", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "save", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "saveJSON", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "saveJSONObject", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "saveJSONArray", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "saveStrings", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "saveTable", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "writeFile", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "downloadFile", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_checkFileExtension", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_isSafari", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_onkeydown", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_onkeyup", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_onkeypress", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_onblur", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "keyIsDown", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_updatePAccelerations", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_updatePRotations", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "setMoveThreshold", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "setShakeThreshold", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_ondeviceorientation", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_ondevicemotion", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_handleMotion", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_updateNextMouseCoords", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_updateMouseCoords", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_setMouseButton", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_onmousemove", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_onmousedown", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_onmouseup", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_ondragend", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_ondragover", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_onclick", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_doubleClicked", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_onwheel", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "day", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "hour", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "minute", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "millis", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "month", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "second", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "year", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_updateTouchCoords", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_ontouchstart", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_ontouchmove", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_ontouchend", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "createVector", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "abs", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "ceil", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "constrain", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "dist", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "exp", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "floor", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "lerp", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "log", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "mag", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "map", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "max", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "min", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "norm", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "pow", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "round", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "sq", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "sqrt", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "randomSeed", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "random", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "randomGaussian", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "noise", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "noiseDetail", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "noiseSeed", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "acos", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "asin", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "atan", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "atan2", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "cos", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "sin", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "tan", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "degrees", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "radians", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "angleMode", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "setAttributes", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "createCanvas", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "resizeCanvas", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "noCanvas", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "createGraphics", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "blendMode", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "arc", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "ellipse", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "line", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "point", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "quad", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "rect", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "triangle", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "ellipseMode", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "noSmooth", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "rectMode", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "smooth", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "strokeCap", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "strokeJoin", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "strokeWeight", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "bezier", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "bezierDetail", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "bezierPoint", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "bezierTangent", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "curve", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "curveDetail", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "curveTightness", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "curvePoint", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "curveTangent", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "beginContour", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "beginShape", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "bezierVertex", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "curveVertex", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "endContour", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "endShape", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "quadraticVertex", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "vertex", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "exit", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "noLoop", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "loop", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "push", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "pop", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "pushStyle", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "popStyle", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "redraw", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "size", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "applyMatrix", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "popMatrix", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "printMatrix", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "pushMatrix", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "resetMatrix", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "rotate", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "rotateX", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "rotateY", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "rotateZ", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "scale", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "shearX", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "shearY", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "translate", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "textAlign", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "textLeading", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "textSize", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "textStyle", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "textWidth", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "textAscent", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "textDescent", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_updateTextMetrics", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "text", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "textFont", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "createStringDict", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "createNumberDict", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "plane", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "box", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "sphere", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "cylinder", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "cone", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "ellipsoid", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "torus", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "model", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "shader", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "normalMaterial", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "texture", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "ambientMaterial", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "specularMaterial", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "ambientLight", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "directionalLight", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "pointLight", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "camera", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "perspective", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "ortho", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "orbitControl", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_start", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_runIfPreloadsAreDone", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_decrementPreload", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_wrapPreload", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_incrementPreload", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_setup", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_draw", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_runFrames", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "_setProperty", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:45213 p5 had problems creating the global function "remove", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.
p5.js:69083 p5.RendererGL: enabled webgl context
p5.js:68869 Uncaught TypeError: Cannot read property 'location' of undefined
    at p5.RendererGL.createBuffers (p5.js:68869)
    at p5.ellipsoid (p5.js:71047)
    at draw (cube.js:8)
    at p5.redraw (p5.js:50266)
    at p5.<anonymous> (p5.js:44917)
    at p5.<anonymous> (p5.js:44812)
    at new p5 (p5.js:45103)
    at _globalInit (p5.js:46862)
p5.RendererGL.createBuffers @ p5.js:68869
p5.ellipsoid @ p5.js:71047
draw @ cube.js:8
p5.redraw @ p5.js:50266
(anonymous) @ p5.js:44917
(anonymous) @ p5.js:44812
p5 @ p5.js:45103
_globalInit @ p5.js:46862

#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version:Chrome, FireFox
- Operating System: Linux 
- Steps to reproduce this:

**Comment by Spongman** [comment]
i believe this is a dupe of #2262, which has been fixed.

**Comment by mlarghydracept** [comment]
closed with #2349

**Comment by Klibrugak** [comment]
I tried with [#2262](https://github.com/processing/p5.js/issues/2262) but it still doesn't work,
may it something related to the free drivers of manjaro?

**Comment by Spongman** [comment]
Can you try with latest master? All those fixes have been merged in recently.

Also, does https://get.webgl.org work?

**Comment by Klibrugak** [comment]
get.webgl.org works fine, the problem is the references in the web page of p5, also I haven't been able to make it work copying the code directly and running it localy.
The browser console in the references page shows this:
<b>
window.controllers/Controllers is deprecated. Do not use it for UA detection.
ace.js:1:18325
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!
reference
p5.RendererGL: enabled webgl context
p5.min.js:37:14206
TypeError: this.curFillShader.attributes.aNormal is undefined
[Learn More]
p5.min.js:37:3960
[105]</d.RendererGL.prototype.createBuffers
https://p5js.org/assets/js/p5.min.js:37:3960
[109]</d.prototype.plane
https://p5js.org/assets/js/p5.min.js:37:31412
draw
https://p5js.org/assets/js/render.js%20line%20209%20%3E%20eval:8:3
[66]</d.prototype.redraw
https://p5js.org/assets/js/p5.min.js:33:29334
e/this._draw<
https://p5js.org/assets/js/p5.min.js:32:16740
<anonymous> self-hosted:951:17 e/this._start<
https://p5js.org/assets/js/p5.min.js:32:15360
<anonymous> self-hosted:951:17 e
https://p5js.org/assets/js/p5.min.js:32:18782
runCode/</<
https://p5js.org/assets/js/render.js:242:20 </b>

and when running my index.html:
<b>

p5.RendererGL: enabled webgl context
p5.js:69083:7
You just changed the value of "registerPreloadMethod", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "registerMethod", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_createFriendlyGlobalFunctionBinder", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_helpForMisusedAtTopLevelCode", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "alpha", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "blue", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "brightness", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "color", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "green", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "hue", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "lerpColor", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "lightness", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "red", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "saturation", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "background", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "clear", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "colorMode", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "fill", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "noFill", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "noStroke", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "stroke", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "float", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "int", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "str", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "boolean", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "byte", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "char", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "unchar", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "hex", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "unhex", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "append", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "arrayCopy", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "concat", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "reverse", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "shorten", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "shuffle", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "sort", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "splice", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "subset", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "join", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "match", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "matchAll", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "nf", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "nfc", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "nfp", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "nfs", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "split", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "splitTokens", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "trim", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "print", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "cursor", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "frameRate", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "getFrameRate", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "setFrameRate", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "noCursor", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_onresize", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "fullscreen", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "pixelDensity", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "displayDensity", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "getURL", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "getURLPath", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "getURLParams", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "createImage", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "saveCanvas", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "saveFrames", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_makeFrame", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "image", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "tint", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "noTint", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_getTintedImageCanvas", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "imageMode", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "blend", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "copy", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "filter", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "get", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "loadPixels", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "set", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "updatePixels", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "parseXML", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "httpGet", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "httpPost", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "httpDo", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "createWriter", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "save", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "saveJSON", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "saveJSONObject", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "saveJSONArray", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "saveStrings", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "saveTable", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "writeFile", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "downloadFile", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_checkFileExtension", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_isSafari", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_onkeydown", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_onkeyup", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_onkeypress", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_onblur", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "keyIsDown", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_updatePAccelerations", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_updatePRotations", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "setMoveThreshold", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "setShakeThreshold", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_ondeviceorientation", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_ondevicemotion", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_handleMotion", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_updateNextMouseCoords", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_updateMouseCoords", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_setMouseButton", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_onmousemove", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_onmousedown", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_onmouseup", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_ondragend", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_ondragover", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_onclick", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_doubleClicked", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_onwheel", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "day", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "hour", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "minute", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "millis", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "month", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "second", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "year", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_updateTouchCoords", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_ontouchstart", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_ontouchmove", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_ontouchend", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "createVector", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "abs", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "ceil", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "constrain", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "dist", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "exp", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "floor", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "lerp", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "log", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "mag", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "map", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "max", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "min", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "norm", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "pow", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "round", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "sq", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "sqrt", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "randomSeed", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "random", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "randomGaussian", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "noise", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "noiseDetail", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "noiseSeed", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "acos", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "asin", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "atan", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "atan2", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "cos", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "sin", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "tan", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "degrees", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "radians", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "angleMode", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "setAttributes", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "createCanvas", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "resizeCanvas", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "noCanvas", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "createGraphics", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "blendMode", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "arc", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "ellipse", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "line", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "point", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "quad", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "rect", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "triangle", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "ellipseMode", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "noSmooth", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "rectMode", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "smooth", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "strokeCap", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "strokeJoin", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "strokeWeight", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "bezier", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "bezierDetail", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "bezierPoint", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "bezierTangent", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "curve", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "curveDetail", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "curveTightness", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "curvePoint", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "curveTangent", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "beginContour", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "beginShape", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "bezierVertex", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "curveVertex", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "endContour", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "endShape", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "quadraticVertex", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "vertex", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "exit", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "noLoop", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "loop", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "push", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "pop", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "pushStyle", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "popStyle", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "redraw", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "size", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "applyMatrix", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "popMatrix", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "printMatrix", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "pushMatrix", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "resetMatrix", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "rotate", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "rotateX", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "rotateY", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "rotateZ", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "scale", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "shearX", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "shearY", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "translate", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "textAlign", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "textLeading", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "textSize", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "textStyle", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "textWidth", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "textAscent", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "textDescent", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_updateTextMetrics", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "text", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "textFont", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "createStringDict", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "createNumberDict", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "plane", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "box", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "sphere", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "cylinder", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "cone", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "ellipsoid", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "torus", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "model", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "shader", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "normalMaterial", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "texture", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "ambientMaterial", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "specularMaterial", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "ambientLight", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "directionalLight", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "pointLight", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "camera", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "perspective", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "ortho", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "orbitControl", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_start", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_runIfPreloadsAreDone", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_decrementPreload", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_wrapPreload", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_incrementPreload", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_setup", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_draw", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_runFrames", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "_setProperty", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
You just changed the value of "remove", which was a p5 function. This could cause problems later if you're not careful.
p5.js:45205:13
p5.RendererGL: enabled webgl context
p5.min.js:37:14206
TypeError: p5 is undefined
[Learn More]
p5.dom.js:71:3
TypeError: a is undefined
[Learn More]
p5.dom.min.js:1:1442
TypeError: p5 is undefined
[Learn More]
p5.sound.js:221:3
TypeError: p5 is undefined
[Learn More]
p5.sound.min.js:3:3216
TypeError: this.curFillShader.attributes.aNormal is undefined
[Learn More]
p5.js:68869:3
TypeError: this.curFillShader.attributes.aNormal is undefined
[Learn More]
p5.min.js:37:3960
</b>

**Comment by Spongman** [comment]
It looks like you might be importing p5.js twice in your html file. Or initializing it twice maybe? Something weird is happening to cause all those errors. Maybe can you post your .html file here?

The error you're seeing on the p5js site is the same as #2262 and has been fixed, but the fix has not yet been released. I'm afraid you're either going to have to wait until the next release, or clone & build p5.js yourself.

**Comment by sjorsvanheuveln** [comment]
I had the same problem with react-p5-wrapper. In my case it got caused by not sending a sketch to the component.
