### ISSUE TITLE
Broken links in wiki

### ISSUE THREAD

**Issue by AbhiGulati** [processing/p5.js#4570]
Some of the links at [the page on optimizing performance](https://github.com/processing/p5.js/wiki/Optimizing-p5.js-Code-for-Performance) appear to be broken, e.g. there's a link to https://github.com/processing/p5.js/blob/master/developer_docs/friendly_error_system.md but it looks like the correct page is at https://github.com/processing/p5.js/blob/master/contributor_docs/friendly_error_system.md.

**Comment by montoyamoraga** [comment]
thank you for noticing it! @AbhiGulati i just fixed it :)

**Comment by montoyamoraga** [comment]
@all-contributors please add @AbhiGulati for doc

**Comment by AbhiGulati** [comment]
@montoyamoraga it looks like some of the links on the wiki are still incorrect. I'm happy to go and fix them, but it appear that I don't yet have permissions to edit the wiki. I saw the MR adding me to the contributors file, and I appear to still be [there](https://github.com/processing/p5.js/blob/main/.all-contributorsrc), but I don't see an "Edit" button or anything on the wiki page.

**Comment by montoyamoraga** [comment]
@AbhiGulati hi thank you for noticing!
the link was broken when you originally pointed it out, because of us changing developer-docs to contributor-docs, and this week we introduced a new change, changing the name of our repository's branch from master to main, i fixed it again :)

i think some of the main contributors have edit access to the wiki, and it made me think it could be better to roll out the wiki and port everything from there to Markdown files in the repo so that they accept pull requests, going to think about it, since i never spend too much time on the wiki, and my guess it's that its content rarely changes :)

**Comment by AbhiGulati** [comment]
Awesome, thanks for updating the links.

Sounds like you don't have a concrete plan for letting external folks contribute to the wiki yet, so if anything comes up in the future I'll just create another issue.

**Comment by montoyamoraga** [comment]
yeah, my guess is the wiki is mostly static, and if you find more roadblocks to contributing, let me know and i will try to give you access
