### ISSUE TITLE
[p5.js 2.0 Beta Bug Report]: await not working for async load functions

### ISSUE THREAD

**Issue by sidwellr** [processing/p5.js#7587]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [x] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### p5.js version

2.0.0-beta.3

### Web browser and version

Brave 1.75.178, Chrome 133.0.6943.142, Firefox 135.0

### Operating system

Windows 10

### Steps to reproduce this

Many of the p5.js load functions don't work correctly with await; they seem to return prematurely. I use loadStrings in the snippet below, but have seen the same problem in loadShader and loadBytes; it is probably an issue with others. In the code below, I use "await loadStrings" to load data from a text file, which should wait until the data is loaded to continue. But printing it immediately prints an empty array. The successCallback works fine; the correct data is printed in the callback function. (But the problem arises even if no callback function is given.)

### Steps:
1. Call await loadStrings (or loadShader or loadBytes) in the async setup function
2. The await should make the function wait until the data is available, but the data is empty

### Snippet:

https://editor.p5js.org/rsidwell/sketches/aVQd6eoOG
```js

let myData;

async function setup() {
  myData = await loadStrings('test.txt', gotData);  
  print(myData);
}

function gotData(d) {
  myData = d;
  print(myData);
}

```

**Comment by dhowe** [comment]
Hi @sidwellr - I think the pattern (and perhaps this needs to be documented better) here is to use _either_ async/await with a return value or the callback, but not both:

```
let myData;

async function setup() {
  myData = await loadStrings('test.txt');  
  print(myData);
}
```
or

```
let myData;

function setup() {
   loadStrings('test.txt', gotData);  
}

function gotData(d) {
  myData = d;
  print(myData);
}
```

**Comment by sidwellr** [comment]
I agree. I only used both to show that callback works but await doesn't. If you leave off the callback (your first snippet), it will print '[]' instead of the lines in test.txt.

**Comment by dhowe** [comment]
I can confirm this in global mode in the editor. In instance mode I see the properly loaded string.

**Comment by limzykenneth** [comment]
Yes, for async/await you should normally not use the callbacks since they serve similar purpose. However, if you want to use callbacks still, you need to return the value of the loaded data in the callback:

```js
let myData;

async function setup() {
  myData = await loadStrings('test.txt', gotData);  
  print(myData);
}

function gotData(d) {
  myData = d;
  print(myData);
  return d;
}
```

This is considered more of an advanced use as the callback can be use as a filter to dynamically modify the loaded data before it is resolved into the promise. In 1.x, there are similar behavior as well in that if the callback is provided the function will not return a value.

We are still in the middle of updating the documentation so this is not fully reflected yet but the behavior is intended..

**Comment by sidwellr** [comment]
@limzykenneth Thanks. I was wondering about that. I was comparing the code for loadImage (which works) and loadStrings (which doesn't), and notice that loadImage returns the result of successCallback if it is defined, but loadStrings doesn't. I doubt that's the problem with the other load functions, but someone should probably verify that all of the load function return the result of successCallback so that the advanced use you describe will work.

**Comment by limzykenneth** [comment]
@sidwellr Yeah that is a bug, I'll check there is a return for all the loading functions. Thanks.

**Comment by limzykenneth** [comment]
@sidwellr 2.0.0-beta.3 has a deployment error making it incorrect, I'm deploying a new version. Can you for now try 2.0.0-beta.2 or wait for a bit until 2.0.0-beta.4 is available? I'll be pulling beta 3 as soon as beta 4 is available as it is incorrect.

**Comment by sidwellr** [comment]
In beta 2, loadStrings works fine. So does loadTable, but the second param is now the character so the example is wrong. And loadBytes works, but again a change: the return value is just an array, not not an object containing an array. so the documentation is wrong.

I still can't get loadShader to work. Has that interface changed (other than returning a promise instead of a shader)?

**Comment by limzykenneth** [comment]
Issues should be fixed with https://github.com/processing/p5.js/pull/7594.

The documentation is updated in the inline reference, do note that the reference on the website p5js.org will not be updated on release of 2.0 but be hosted separately to support a smooth transition, which means for now (until we finished with the beta site containing 2.0 reference) the inline reference contained alongside the source is the source of truth.

**Comment by sidwellr** [comment]
Should the fix be in beta 4? Because it still doesn't seem to work. I tried the code in the inline reference; see https://editor.p5js.org/rsidwell/sketches/qEvxHQ7m4.

**Comment by limzykenneth** [comment]
It should be in the next beta release.

**Comment by limzykenneth** [comment]
Closed by #7594
