### ISSUE TITLE
p5.Graphics and copy()

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js#995]
I'm testing an example where I'm using `copy()` with `createGraphics()`.  `copy()` works as expected with `p5.Image`.

``` javascript
var img = createImage(100, 100);
copy(img, 0, 0, 100, 100, 0, 0, 100, 100);
```

but does not work with `p5.Graphics`.

``` javascript
var graphics = createImage(100, 100);
copy(graphics, 0, 0, 100, 100, 0, 0, 100, 100);
```

It fails on this line in `copyHelper()`

``` javascript
  var s = srcImage.canvas.width / srcImage.width;
```

I believe I just need to detect the argument type `p5.Graphics` object or `p5.Image`, something like:

``` javascript
p5.Renderer2D._copyHelper =
function (srcImage, sx, sy, sw, sh, dx, dy, dw, dh) {
  var canvas;
  if (srcImage instanceof p5.Image) {
    canvas = srcImage.canvas;
  } else if (srcImage instanceof p5.Graphics) {
    canvas = srcImage.elt;
  }
  var s = canvas.width / srcImage.width;
  this.drawingContext.drawImage(canvas,
    s * sx, s * sy, s * sw, s * sh, dx, dy, dw, dh);
};
```

This should work, but for whatever reason, `this.drawingContext` is pointing to the canvas made with `createGraphics()` when `copy()` is called and not the actual default p5 canvas!  I'm a little stuck.

Am I making sense?  Can anyone shed any light?  I believe `copy()` should support `p5.Graphics`, yes?

**Comment by laurentoget** [comment]
I thought trying to figure this out would be a good way to make myself familiar with the code base (great project btw, nice to meet you all), but after 30 minutes in the code, i am still utterly confused. Feels to me like a good moment to put of moratorium on the use of instanceof until someone who understands the relationship between canvas, renderer and drawingcontext makes a drawing for the rest of the world.

**Comment by lmccart** [comment]
@shiffman is copy supposed to work for p5.Graphics? looking at the processing reference, it looks like it only supports PImage? or does it also work for PGraphics?

**Comment by lmccart** [comment]
@shiffman well, the above question aside, I think your fix was really close. I got the following code to work:

```javascript
function setup() {
  createCanvas(400, 400);
  background(0);
  var img = createGraphics(100, 100);
  img.ellipse(50, 50, 50, 50);
  copy(img, 0, 0, 100, 100, 0, 0, 100, 100);
  updatePixels();
}
```

with this patch:
```javascript
p5.Renderer2D._copyHelper =
function (srcImage, sx, sy, sw, sh, dx, dy, dw, dh) {
  var canvas;
  if (srcImage instanceof p5.Image) {
    canvas = srcImage.canvas;
  } else if (srcImage instanceof p5.Graphics) {
    srcImage.loadPixels();
    canvas = srcImage.elt;
  }
  var s = canvas.width / srcImage.width;
  this.drawingContext.drawImage(canvas,
    s * sx, s * sy, s * sw, s * sh, dx, dy, dw, dh);
};
```

the key is the `srcImage.loadPixels()` call I added in there. note that I also had to call `updatePixels()` at the end of draw to get it to show up, is this correct behavior or maybe this should be called in `_copyHelper()` as well?

**Comment by lmccart** [comment]
@laurentoget thank you for having a go at this. I hear your concern and we are in the process of writing up better developer documentation. it's just a matter of finding time to do all the things we want to with the volunteers and hours we have to work on this. :)

**Comment by shiffman** [comment]
Ah, you are right.  I just *assumed* you could `copy()` a `PGraphics` object because, well, why wouldn't you?  But in fact it is not supported.  I discovered, however, that `set()` and `get()` work with `PGraphics` in Processing. . . but `p5.Graphics`.   Except that actually I do get it to work back in 0.4.9, but not in anything post 0.4.10.

The thing I'm trying to do is grab the pixels of an image loaded with `createImg()` rather than `loadImage()`.  So the working code I do have in 0.4.9 is as follows:

```javascript
var img;

function setup() {
  createCanvas(400, 300);
  background(0);
  img = createImg('sunflower.jpg', created);
}

function created() {
  graphics = createGraphics(img.width, img.height);
  graphics.image(img, 0, 0, graphics.width, graphics.height);
  var pix = graphics.get(0, 0, 50, 50);
  image(pix, 0, 0);
}
```

So I think there are two questions / issues:

1. I think this is a bug?  `get()` should work as above in 0.4.15.

2. Is there a better way to get access to the pixels of an image loaded with `createImg()`.  Could `get()` or `copy()` be applied directly to a `<img>` `p5.Element`?

**Comment by laurentoget** [comment]
I do not understand this enough to figure why but I suspect adding either graphics.loadPixels or img.loadPixels will get this working.

**Comment by lmccart** [comment]
I just pushed a patch which should fix problem 1. I don't think there's a better way than what you have above, but I'd be open to adding something if we could think of something intuitive and not too hacky.

**Comment by shiffman** [comment]
I sometimes wonder how much magic we should make happen behind the scenes with `loadImage()` and   urls.  For example, we could detect a URL as argument to `loadImage()`, use `createImg()` behind the scenes, hide the element, and copy the pixels into a `p5.Image` object sending it into the callback.

But this is probably too much magic and leaves users open to other problems and confusion about how things work later?  We can leave this open for a bit to think about it, but I think best to see how things go with student projects and where trouble arises (or doesn't) before adding in functionality like this.

**Comment by lmccart** [comment]
sounds good. what do you recommend in terms of supporting p5.Graphics in copy? I can add that patch in if it makes sense. we should then probably close this issue or at least update to reflect the current question. though if it is more of an open question/thinking point maybe it's better just to close it completely and keep it floating in our heads, and reopen at the end of the semester if it seems useful to implement something.

**Comment by shiffman** [comment]
While trying out a workaround related to #1022, I found that I wanted access to the `p5.Graphics`

**Comment by shiffman** [comment]
While trying out a workaround related to #1022, I attempted to get access to the pixels of a `p5.Graphics` object, i.e.

```javascript
function setup() {
  createCanvas(200, 200);
  background(0);
  var g = createGraphics(100, 100);
  g.background(255, 0, 0);
  g.loadPixels();
  image(g, 0, 0);
  console.log(g.pixels);
}
```

The console shows:

```
[]
```

I think this is probably the same question as this issue?  Should we support `copy()` and `loadPixels()` and `pixels` for `p5.Graphics` objects?  I'm now really leaning towards yes!

**Comment by lmccart** [comment]
yes, `pixels()` and `loadPixels()` should be supported, this is a bug. I can add the `copy()` support in there as well.

**Comment by Dolphin101546015** [comment]
Have same problem in final processing release.
With patch applying issue was fixed.
Make changes in release please!

**Comment by BenjaminHabert** [comment]
Is there still an issue here ? It is unclear what needs fixing, can someone rephrase it ?

I [reproduced in the p5 web editor](https://alpha.editor.p5js.org/BenjaminHabert/sketches/B11AxIFcz
) the previously shown snippets that used to fail and they all seem to work:

- `copy()` image and graphics to canvas
- `copy()` and `image()` image to graphics
- `copy()` and `image()` graphics to graphics (note: in the latter case the scaling is wrong, which seems related to #2077)
- `image()` an image from `createImg()` to graphics
- `get()` portion of a graphics
- `loadPixels()` and `.pixels` of a graphics

**Comment by shiffman** [comment]
I think this issue can be closed? It was a lovely discussion but it does appear it's all been resolved?

**Comment by limzykenneth** [comment]
Let's close this, if anything else seem wrong, just open a new issue for that specific problem 😃

**Comment by ricardomatias** [comment]
In the following example there's the case I'd like to argue. This behavior is quite obscure, where `P5Graphics` doesn't have a `copy` method which allows copying an external pixel buffer onto itself. My first thought was, what if I want to copy multiple times into different `P5Graphics`?

In my opinion, `copy` should be part of the `P5Graphics` class.

```js
const image = p5.loadImage('assets/monkey.jpg');
const fbo = p5.createGraphics(width, height);

fbo.copy(image, 0, 0, 50, 50, 0, 0, 50, 50); // does not work

p5.image(fbo, 0, 0); // nothing is drawn

p5.copy(image, 0, 0, 50, 50, 0, 0, 50, 50); // works

p5.image(fbo, 0, 0); // voila!
```
